name: Deploy to VPS

on:
  push:
    branches:
      - vps

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout de la rama vps
      - name: Checkout vps branch
        uses: actions/checkout@v3
        with:
          ref: vps

      # Paso 2: Desplegar al VPS usando SCP
      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.5
        with:
          host: 31.220.108.234
          username: deployuser
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          source: "."  # En la rama vps, el contenido de build está en el root
          target: "/var/www/lareverie/"

      # Paso 3: Reiniciar Nginx en el VPS
      - name: Restart Nginx
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 31.220.108.234
          username: deployuser
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            sudo systemctl reload nginx